name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./app

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Create .env file
      run: |
          touch .env
          echo REACT_APP_FAIROSHOST=https://fairos.fairdatasociety.org/v1/ >> .env
          echo REACT_APP_FAIRDRIVEHOST=https://app.fairdrive.io >> .env
          echo REACT_APP_NAME=Fairphoto >> .env
          cat .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - name: build
      run: yarn build
      env:
        CI: false
    - run: yarn deploy
